-- ============================================================================
-- DENORMALIZED DATABASE SEED DATA
-- Updated for new denormalized schema with multi-language fields and embedded data
-- ============================================================================

-- ============================================================================
-- 1. CHARACTERS (With Multi-Language Fields)
-- ============================================================================

INSERT INTO `characters` (
  `id`, `unique_key`, 
  `name_jp`, `name_en`, `name_cn`, `name_tw`, `name_kr`,
  `age_jp`, `age_en`, `age_cn`, `age_tw`, `age_kr`,
  `birthday_jp`, `birthday_en`, `birthday_cn`, `birthday_tw`, `birthday_kr`,
  `height_jp`, `height_en`, `height_cn`, `height_tw`, `height_kr`,
  `measurements_jp`, `measurements_en`, `measurements_cn`, `measurements_tw`, `measurements_kr`,
  `blood_jp`, `blood_en`, `blood_cn`, `blood_tw`, `blood_kr`,
  `job_jp`, `job_en`, `job_cn`, `job_tw`, `job_kr`,
  `hobby_jp`, `hobby_en`, `hobby_cn`, `hobby_tw`, `hobby_kr`,
  `food_jp`, `food_en`, `food_cn`, `food_tw`, `food_kr`,
  `color_jp`, `color_en`, `color_cn`, `color_tw`, `color_kr`,
  `cast_jp`, `cast_en`, `cast_cn`, `cast_tw`, `cast_kr`,
  `is_active`, `game_version`
) VALUES
-- Marie Rose
(1, 'marie-rose',
 'マリー・ローズ', 'Marie Rose', '玛莉萝丝', '瑪莉蘿絲', '마리 로즈',
 '18歳', '18 years old', '18岁', '18歲', '18세',
 '6月6日', 'June 6', '6月6日', '6月6日', '6월 6일',
 '147cm', '147cm', '147厘米', '147公分', '147cm',
 'B74/W56/H78', 'B74/W56/H78', 'B74/W56/H78', 'B74/W56/H78', 'B74/W56/H78',
 'AB型', 'AB', 'AB型', 'AB型', 'AB형',
 'ゴシックロリータ', 'Gothic Lolita', '哥特萝莉', '哥德蘿莉', '고딕 로리타',
 'お菓子作り', 'Making sweets', '制作甜点', '製作甜點', '과자 만들기',
 'チーズケーキ', 'Cheesecake', '芝士蛋糕', '起司蛋糕', '치즈케이크',
 'ピンク', 'Pink', '粉红色', '粉紅色', '핑크',
 '相沢舞', 'Mai Aizawa', '相泽舞', '相澤舞', '아이자와 마이',
 1, '1.0.0'),

-- Honoka
(2, 'honoka',
 'ほのか', 'Honoka', '穗香', '穗香', '호노카',
 '18歳', '18 years old', '18岁', '18歲', '18세',
 '3月24日', 'March 24', '3月24日', '3月24日', '3월 24일',
 '150cm', '150cm', '150厘米', '150公分', '150cm',
 'B99/W58/H91', 'B99/W58/H91', 'B99/W58/H91', 'B99/W58/H91', 'B99/W58/H91',
 'AB型', 'AB', 'AB型', 'AB型', 'AB형',
 '女子高生', 'High School Student', '女高中生', '女高中生', '여고생',
 'ビーチバレー', 'Beach Volleyball', '沙滩排球', '沙灘排球', '비치발리볼',
 'おにぎり', 'Rice Balls', '饭团', '飯糰', '주먹밥',
 'オレンジ', 'Orange', '橙色', '橙色', '오렌지',
 '野中藍', 'Ai Nonaka', '野中蓝', '野中藍', '노나카 아이',
 1, '1.0.0'),

-- Kasumi
(3, 'kasumi',
 'かすみ', 'Kasumi', '霞', '霞', '카스미',
 '17歳', '17 years old', '17岁', '17歲', '17세',
 '2月23日', 'February 23', '2月23日', '2月23日', '2월 23일',
 '158cm', '158cm', '158厘米', '158公分', '158cm',
 'B89/W54/H85', 'B89/W54/H85', 'B89/W54/H85', 'B89/W54/H85', 'B89/W54/H85',
 'O型', 'O', 'O型', 'O型', 'O형',
 '忍者', 'Ninja', '忍者', '忍者', '닌자',
 '修行', 'Training', '修行', '修行', '수행',
 'いちご', 'Strawberries', '草莓', '草莓', '딸기',
 '青', 'Blue', '蓝色', '藍色', '파랑',
 '桑島法子', 'Houko Kuwashima', '桑岛法子', '桑島法子', '쿠와시마 호코',
 1, '1.1.0'),

-- Misaki
(4, 'misaki',
 'みさき', 'Misaki', '海咲', '海咲', '미사키',
 '18歳', '18 years old', '18岁', '18歲', '18세',
 '7月7日', 'July 7', '7月7日', '7月7日', '7월 7일',
 '160cm', '160cm', '160厘米', '160公分', '160cm',
 'B85/W55/H86', 'B85/W55/H86', 'B85/W55/H86', 'B85/W55/H86', 'B85/W55/H86',
 'B型', 'B', 'B型', 'B型', 'B형',
 'オーナー', 'Owner', '老板', '老闆', '오너',
 '写真撮影', 'Photography', '摄影', '攝影', '사진 촬영',
 'パンケーキ', 'Pancakes', '煎饼', '煎餅', '팬케이크',
 '水色', 'Aqua', '水蓝色', '水藍色', '하늘색',
 '津田美波', 'Minami Tsuda', '津田美波', '津田美波', '츠다 미나미',
 1, '1.0.0'),

-- Shandy
(5, 'shandy',
 'シャンディ', 'Shandy', 'シャンディ', 'シャンディ', '샨디',
 '19歳', '19 years old', '19岁', '19歲', '19세',
 '4月2日', 'April 2', '4月2日', '4月2日', '4월 2일',
 '177cm', '177cm', '177厘米', '177公分', '177cm',
 'B99/W60/H92', 'B99/W60/H92', 'B99/W60/H92', 'B99/W60/H92', 'B99/W60/H92',
 'O型', 'O', 'O型', 'O型', 'O형',
 'プロビーチバレー選手', 'Pro Beach Volleyball Player', '职业沙滩排球选手', '職業沙灘排球選手', '프로 비치발리볼 선수',
 'サーフィン', 'Surfing', '冲浪', '衝浪', '서핑',
 'バーベキュー', 'BBQ', '烧烤', '燒烤', '바비큐',
 '黄色', 'Yellow', '黄色', '黃色', '노랑',
 '下地紫野', 'Shino Shimoji', '下地紫野', '下地紫野', '시모지 시노',
 1, '4.12.0'),

-- Ayane
(6, 'ayane',
 'あやね', 'Ayane', '绫音', '綾音', '아야네',
 '18歳', '18 years old', '18岁', '18歲', '18세',
 '8月27日', 'August 27', '8月27日', '8月27日', '8월 27일',
 '157cm', '157cm', '157厘米', '157公分', '157cm',
 'B95/W54/H85', 'B95/W54/H85', 'B95/W54/H85', 'B95/W54/H85', 'B95/W54/H85',
 'A型', 'A', 'A型', 'A型', 'A형',
 '忍者', 'Ninja', '忍者', '忍者', '닌자',
 '読書', 'Reading', '阅读', '閱讀', '독서',
 'ぶどう', 'Grapes', '葡萄', '葡萄', '포도',
 '紫', 'Purple', '紫色', '紫色', '보라',
 '山崎和佳奈', 'Wakana Yamazaki', '山崎和佳奈', '山崎和佳奈', '야마자키 와카나',
 1, '1.2.0'),

-- Helena
(7, 'helena',
 'ヘレナ', 'Helena', '海伦娜', '海倫娜', '헬레나',
 '21歳', '21 years old', '21岁', '21歲', '21세',
 '1月30日', 'January 30', '1月30日', '1月30日', '1월 30일',
 '170cm', '170cm', '170厘米', '170公分', '170cm',
 'B90/W59/H89', 'B90/W59/H89', 'B90/W59/H89', 'B90/W59/H89', 'B90/W59/H89',
 'AB型', 'AB', 'AB型', 'AB型', 'AB형',
 'オペラ歌手', 'Opera Singer', '歌剧歌手', '歌劇歌手', '오페라 가수',
 'オペラ鑑賞', 'Opera Appreciation', '欣赏歌剧', '欣賞歌劇', '오페라 감상',
 'マカロン', 'Macarons', '马卡龙', '馬卡龍', '마카롱',
 '白', 'White', '白色', '白色', '하양',
 '小松由佳', 'Yuka Komatsu', '小松由佳', '小松由佳', '코마츠 유카',
 1, '1.3.0'),

-- Kokoro
(8, 'kokoro',
 'こころ', 'Kokoro', '心', '心', '코코로',
 '17歳', '17 years old', '17岁', '17歲', '17세',
 '4月27日', 'April 27', '4月27日', '4月27日', '4월 27일',
 '157cm', '157cm', '157厘米', '157公分', '157cm',
 'B88/W57/H86', 'B88/W57/H86', 'B88/W57/H86', 'B88/W57/H86', 'B88/W57/H86',
 'O型', 'O', 'O型', 'O型', 'O형',
 '芸妓見習い', 'Geisha Apprentice', '艺妓学徒', '藝妓學徒', '게이샤 견습생',
 '日本舞踊', 'Japanese Dance', '日本舞蹈', '日本舞蹈', '일본 무용',
 '和菓子', 'Japanese Sweets', '日式点心', '日式點心', '일본 과자',
 '桜色', 'Cherry Blossom', '樱花色', '櫻花色', '벚꽃색',
 '井口裕香', 'Yuka Iguchi', '井口裕香', '井口裕香', '이구치 유카',
 1, '1.4.0'),

-- Hitomi
(9, 'hitomi',
 'ひとみ', 'Hitomi', '瞳', '瞳', '히토미',
 '18歳', '18 years old', '18岁', '18歲', '18세',
 '5月25日', 'May 25', '5月25日', '5月25日', '5월 25일',
 '160cm', '160cm', '160厘米', '160公分', '160cm',
 'B90/W58/H85', 'B90/W58/H85', 'B90/W58/H85', 'B90/W58/H85', 'B90/W58/H85',
 'A型', 'A', 'A型', 'A型', 'A형',
 '空手家', 'Karateka', '空手家', '空手家', '가라테카',
 '空手', 'Karate', '空手道', '空手道', '가라테',
 'カレーライス', 'Curry Rice', '咖喱饭', '咖哩飯', '카레라이스',
 '緑', 'Green', '绿色', '綠色', '초록',
 '光吉猛修', 'Kotono Mitsuishi', '光吉猛修', '光吉猛修', '미츠이시 코토노',
 1, '1.5.0'),

-- Lei Fang
(10, 'leifang',
 'リー・ファン', 'Lei Fang', '李芳', '李芳', '리판',
 '19歳', '19 years old', '19岁', '19歲', '19세',
 '4月18日', 'April 18', '4月18日', '4月18日', '4월 18일',
 '162cm', '162cm', '162厘米', '162公分', '162cm',
 'B83/W53/H82', 'B83/W53/H82', 'B83/W53/H82', 'B83/W53/H82', 'B83/W53/H82',
 'B型', 'B', 'B型', 'B型', 'B형',
 '大学生', 'University Student', '大学生', '大學生', '대학생',
 '太極拳', 'Tai Chi', '太极拳', '太極拳', '태극권',
 '麻婆豆腐', 'Mapo Tofu', '麻婆豆腐', '麻婆豆腐', '마파두부',
 '赤', 'Red', '红色', '紅色', '빨강',
 '堀江由衣', 'Yui Horie', '堀江由衣', '堀江由衣', '호리에 유이',
 1, '1.6.0');

-- ============================================================================
-- 2. ITEMS (New Denormalized Structure)
-- ============================================================================

INSERT INTO `items` (
  `id`, `unique_key`,
  `name_jp`, `name_en`, `name_cn`, `name_tw`, `name_kr`,
  `type`, `description`, `icon_small`, `icon_large`
) VALUES
(1, 'v-stone-free',
 'Vストーン(無償)', 'V-Stone (Free)', 'V宝石(免费)', 'V寶石(免費)', 'V스톤(무료)',
 'CURRENCY', 'A special currency used for gachas. Obtained from events, login bonuses, and missions.',
 'vstone_small.png', 'vstone_large.png'),

(2, 'zack-money',
 'ザックマネー', 'Zack Money', '扎克钱', '札克錢', '잭 머니',
 'CURRENCY', 'Standard currency for upgrading and buying items. Earned by playing matches and selling items.',
 'zackmoney_small.png', 'zackmoney_large.png'),

(3, 'pow-stone-ssr',
 'POW強化石(SSR)', 'POW Upgrade Stone (SSR)', 'POW强化石(SSR)', 'POW強化石(SSR)', 'POW 강화석(SSR)',
 'UPGRADE_MATERIAL', 'Used to upgrade POW-type swimsuits. Available from event shops and daily matches.',
 'powstone_ssr_small.png', 'powstone_ssr_large.png'),

(4, 'tec-crystal-sr',
 'TEC強化結晶(SR)', 'TEC Upgrade Crystal (SR)', 'TEC强化结晶(SR)', 'TEC強化結晶(SR)', 'TEC 강화 결정(SR)',
 'UPGRADE_MATERIAL', 'Used to upgrade TEC-type swimsuits. Available from event shops and daily matches.',
 'teccrystal_sr_small.png', 'teccrystal_sr_large.png'),

(5, 'cheesecake',
 'チーズケーキ', 'Cheesecake', '芝士蛋糕', '起司蛋糕', '치즈 케이크',
 'GIFT', 'A gift that Marie Rose loves. Available in the shop.',
 'cheesecake_small.png', 'cheesecake_large.png'),

(6, 'fp-refill-100',
 'FP回復ドリンク100', 'FP Refill Drink (100)', 'FP回复饮料100', 'FP回復飲料100', 'FP 회복 드링크 100',
 'CONSUMABLE', 'Restores 100 FP. Obtained from login bonuses and owner shop.',
 'fprefill_small.png', 'fprefill_large.png'),

(7, 'starlight-coin-2023',
 '星明かりのコイン2023', 'Starlight Coin 2023', '星光硬币2023', '星光硬幣2023', '별빛 코인 2023',
 'CURRENCY', 'Can be exchanged for items in the Starlight Ocean Festival event shop.',
 'starlightcoin_small.png', 'starlightcoin_large.png'),

(8, 'ssr-unlock-stone',
 'SSR覚醒石', 'SSR Awaken Stone', 'SSR觉醒石', 'SSR覺醒石', 'SSR 각성석',
 'UPGRADE_MATERIAL', 'Used to awaken an SSR swimsuit to its maximum level. Available from VIP Shop and high-tier event rewards.',
 'ssrawaken_small.png', 'ssrawaken_large.png'),

(9, 'stm-crystal-sr',
 'STM強化結晶(SR)', 'STM Upgrade Crystal (SR)', 'STM强化结晶(SR)', 'STM強化結晶(SR)', 'STM 강화 결정(SR)',
 'UPGRADE_MATERIAL', 'Used to upgrade STM-type swimsuits. Available from event shops and daily matches.',
 'stmcrystal_sr_small.png', 'stmcrystal_sr_large.png'),

(10, 'apl-crystal-ssr',
 'APL強化結晶(SSR)', 'APL Upgrade Crystal (SSR)', 'APL强化结晶(SSR)', 'APL強化結晶(SSR)', 'APL 강화 결정(SSR)',
 'UPGRADE_MATERIAL', 'Used to upgrade APL-type swimsuits. Available from VIP Shop and high-tier events.',
 'aplcrystal_ssr_small.png', 'aplcrystal_ssr_large.png'),

(11, 'chocolate-cake',
 'チョコレートケーキ', 'Chocolate Cake', '巧克力蛋糕', '巧克力蛋糕', '초콜릿 케이크',
 'GIFT', 'A sweet gift that most characters enjoy. Available in shop and events.',
 'chocolatecake_small.png', 'chocolatecake_large.png'),

(12, 'diamond-necklace',
 'ダイヤモンドネックレス', 'Diamond Necklace', '钻石项链', '鑽石項鍊', '다이아몬드 목걸이',
 'ACCESSORY', 'A luxurious accessory that increases Appeal stats. Available from VIP Shop and special events.',
 'diamondnecklace_small.png', 'diamondnecklace_large.png'),

(13, 'owner-points',
 'オーナーポイント', 'Owner Points', '老板积分', '老闆積分', '오너 포인트',
 'CURRENCY', 'Points earned from various activities that can be spent in the Owner Shop.',
 'ownerpoints_small.png', 'ownerpoints_large.png'),

(14, 'trendy-voucher',
 'トレンド券', 'Trendy Voucher', '潮流券', '潮流券', '트렌드 바우처',
 'CURRENCY', 'Special tickets used for Trendy gacha pulls. Obtained from festival events and special promotions.',
 'trendyvoucher_small.png', 'trendyvoucher_large.png'),

(15, 'birthday-gift-box',
 'バースデーギフトボックス', 'Birthday Gift Box', '生日礼品盒', '生日禮品盒', '생일 선물 상자',
 'CONSUMABLE', 'A special gift box containing random birthday-themed items. Available during birthday events.',
 'birthdaygift_small.png', 'birthdaygift_large.png');

-- ============================================================================
-- 3. SWIMSUITS (With Embedded Skills and Stats)
-- ============================================================================

INSERT INTO `swimsuits` (
  `id`, `character_key`, `unique_key`,
  `name_jp`, `name_en`, `name_cn`, `name_tw`, `name_kr`,
  `rarity`, `attribute`,
  `base_pow`, `max_pow`, `pow_growth`,
  `base_tec`, `max_tec`, `tec_growth`,
  `base_stm`, `max_stm`, `stm_growth`,
  `base_apl`, `max_apl`, `apl_growth`,
  `skill_id_1`, `skill_key_1`, `skill_name_jp_1`, `skill_name_en_1`, `skill_name_cn_1`, `skill_name_tw_1`, `skill_name_kr_1`,
  `skill_des_1`, `skill_des_jp_1`, `skill_des_en_1`, `skill_des_cn_1`, `skill_des_tw_1`, `skill_des_kr_1`,
  `skill_id_2`, `skill_key_2`, `skill_name_jp_2`, `skill_name_en_2`, `skill_name_cn_2`, `skill_name_tw_2`, `skill_name_kr_2`,
  `skill_des_2`, `skill_des_jp_2`, `skill_des_en_2`, `skill_des_cn_2`, `skill_des_tw_2`, `skill_des_kr_2`,
  `skill_id_3`, `skill_key_3`, `skill_name_jp_3`, `skill_name_en_3`, `skill_name_cn_3`, `skill_name_tw_3`, `skill_name_kr_3`,
  `skill_des_3`, `skill_des_jp_3`, `skill_des_en_3`, `skill_des_cn_3`, `skill_des_tw_3`, `skill_des_kr_3`,
  `bromide`, `cossbreak_bromide`
) VALUES
-- Marie Rose - Stellar Aquarius (SSR TEC)
(1, 'marie-rose', 'ssr-marie-stellar-aquarius',
 'ステラ・アクエリアス', 'Stellar Aquarius', '星光水瓶', '星光水瓶', '스텔라 아쿠아리우스',
 'SSR', 'TEC',
 1200, 1800, 12,
 1800, 2800, 18,
 1400, 2100, 14,
 1300, 2000, 13,
 1, 'fever-skill-tec-1', 'TECフィーバースキル', 'TEC Fever Skill', '技巧型狂热技能', '技巧型狂熱技能', '테크닉 피버 스킬',
 'When attacking, high chance to trigger a Feint. Increases TEC by 40%.',
 'アタック時、高確率でフェイントを発動。TECが40%アップ。',
 'When attacking, high chance to trigger a Feint. Increases TEC by 40%.',
 '攻击时，高概率触发佯攻。技巧提升40%。',
 '攻擊時，高機率觸發佯攻。技巧提升40%。',
 '공격 시, 높은 확률로 페인트 발동. 테크닉 40% 상승.',
 5, 'tec-boost-l', 'テクニックアップL', 'Technique Boost (L)', '技巧提升(大)', '技巧提升(大)', '테크닉 업(L)',
 'Increases TEC by 15%.',
 'TECが15%アップ。',
 'Increases TEC by 15%.',
 '技巧提升15%。',
 '技巧提升15%。',
 '테크닉 15% 상승.',
 10, 'energy-save', 'エナジーセーブ', 'Energy Save', '能量节约', '能量節約', '에너지 세이브',
 'Reduces stamina consumption by 20%.',
 'スタミナ消費を20%軽減。',
 'Reduces stamina consumption by 20%.',
 '耐力消耗减少20%。',
 '耐力消耗減少20%。',
 '스태미너 소비 20% 감소.',
 'stellar-aquarius-bromide', 'stellar-aquarius-malfunction-bromide'),

-- Honoka - Bouquet Plumeria (SSR+ TEC)
(2, 'honoka', 'ssr-honoka-bouquet-plumeria',
 'ブーケ・プルメリア', 'Bouquet Plumeria', '花束鸡蛋花', '花束雞蛋花', '부케 플루메리아',
 'SSR+', 'TEC',
 1300, 2000, 13,
 2000, 3200, 20,
 1500, 2300, 15,
 1400, 2200, 14,
 2, 'fever-skill-tec-1', 'TECフィーバースキル', 'TEC Fever Skill', '技巧型狂热技能', '技巧型狂熱技能', '테크닉 피버 스킬',
 'When attacking, high chance to trigger a Feint. Increases TEC by 40%.',
 'アタック時、高確率でフェイントを発動。TECが40%アップ。',
 'When attacking, high chance to trigger a Feint. Increases TEC by 40%.',
 '攻击时，高概率触发佯攻。技巧提升40%。',
 '攻擊時，高機率觸發佯攻。技巧提升40%。',
 '공격 시, 높은 확률로 페인트 발동. 테크닉 40% 상승.',
 7, 'appeal-technique-pp', 'アピールテクニック++', 'Appeal Technique++', 'アピールテクニック++', 'アピールテクニック++', 'アピールテクニック++',
 'Increases TEC by 25% if suit has Malfunction.',
 'マルファンクション時、TECが25%アップ。',
 'Increases TEC by 25% if suit has Malfunction.',
 '故障时技巧提升25%。',
 '故障時技巧提升25%。',
 '말펑션 시 테크닉 25% 상승.',
 17, 'all-round-boost-m', 'オールラウンドアップM', 'All-Round Boost (M)', '全能提升(中)', '全能提升(中)', '올라운드 업(M)',
 'Increases all base stats by 8%.',
 '全ステータスが8%アップ。',
 'Increases all base stats by 8%.',
 '全属性提升8%。',
 '全屬性提升8%。',
 '모든 스탯 8% 상승.',
 'bouquet-plumeria-bromide', 'bouquet-plumeria-malfunction-bromide'),

-- Kasumi - Tattered Ninja (SSR POW)
(3, 'kasumi', 'ssr-kasumi-tattered-ninja',
 'かすみの忍び装束・破', 'Kasumi''s Tattered Ninja Garb', '霞的破损忍装', '霞的破損忍裝', '카스미의 낡은 닌자복',
 'SSR', 'POW',
 2200, 3400, 22,
 1300, 2000, 13,
 1400, 2100, 14,
 1200, 1800, 12,
 1, 'fever-skill-pow-1', 'POWフィーバースキル', 'POW Fever Skill', '力量型狂热技能', '力量型狂熱技能', '파워 피버 스킬',
 'When attacking, high chance to trigger a Spike. Increases POW by 40%.',
 'アタック時、高確率でスパイクを発動。POWが40%アップ。',
 'When attacking, high chance to trigger a Spike. Increases POW by 40%.',
 '攻击时，高概率触发杀球。力量提升40%。',
 '攻擊時，高機率觸發殺球。力量提升40%。',
 '공격 시, 높은 확률로 스파이크 발동. 파워 40% 상승.',
 3, 'powerful-spike-1', 'パワフルスパイク', 'Powerful Spike', '强力杀球', '強力殺球', '강력 스파이크',
 'When a Spike is successful, POW increases by 20% for this point.',
 'スパイク成功時、このポイント中POWが20%アップ。',
 'When a Spike is successful, POW increases by 20% for this point.',
 '杀球成功时，本回合力量提升20%。',
 '殺球成功時，本回合力量提升20%。',
 '스파이크 성공 시, 이 포인트 동안 파워 20% 상승.',
 13, 'pow-boost-xl', 'パワーアップXL', 'Power Boost (XL)', '力量提升(特大)', '力量提升(特大)', '파워 업(XL)',
 'Increases POW by 20%.',
 'POWが20%アップ。',
 'Increases POW by 20%.',
 '力量提升20%。',
 '力量提升20%。',
 '파워 20% 상승.',
 'kasumi-ninja-bromide', NULL),

-- Misaki - Ocean Goddess (SSR STM)
(4, 'misaki', 'ssr-misaki-ocean-goddess',
 'オーシャンゴッデス', 'Ocean Goddess', '海洋女神', '海洋女神', '오션 고데스',
 'SSR', 'STM',
 1400, 2100, 14,
 1300, 2000, 13,
 2100, 3300, 21,
 1200, 1900, 12,
 11, 'fever-skill-stm-1', 'STMフィーバースキル', 'STM Fever Skill', 'STM狂热技能', 'STM狂熱技能', 'STM 피버 스킬',
 'When defending, high chance to trigger a Block. Increases STM by 40%.',
 'ディフェンス時、高確率でブロックを発動。STMが40%アップ。',
 'When defending, high chance to trigger a Block. Increases STM by 40%.',
 '防守时，高概率触发拦网。耐力提升40%。',
 '防守時，高機率觸發攔網。耐力提升40%。',
 '수비 시, 높은 확률로 블록 발동. 스태미너 40% 상승.',
 4, 'stm-boost-m', 'スタミナアップM', 'Stamina Boost (M)', '耐力提升(中)', '耐力提升(中)', '스태미너 업(M)',
 'Increases initial Stamina by 10%.',
 '初期スタミナが10%アップ。',
 'Increases initial Stamina by 10%.',
 '初始耐力提升10%。',
 '初始耐力提升10%。',
 '초기 스태미너 10% 상승.',
 19, 'quick-recovery', 'クイックリカバリー', 'Quick Recovery', '快速恢复', '快速恢復', '퀵 리커버리',
 'Stamina regenerates 50% faster between points.',
 'ポイント間のスタミナ回復速度が50%アップ。',
 'Stamina regenerates 50% faster between points.',
 '回合间耐力恢复速度提升50%。',
 '回合間耐力恢復速度提升50%。',
 '포인트 사이 스태미너 회복 속도 50% 상승.',
 'ocean-goddess-bromide', 'ocean-goddess-malfunction-bromide'),

-- Shandy - Solar Flare (SSR POW)
(5, 'shandy', 'ssr-shandy-solar-flare',
 'ソーラーフレア', 'Solar Flare', '太阳耀斑', '太陽耀斑', '솔라 플레어',
 'SSR', 'POW',
 2400, 3600, 24,
 1200, 1900, 12,
 1500, 2300, 15,
 1300, 2000, 13,
 1, 'fever-skill-pow-1', 'POWフィーバースキル', 'POW Fever Skill', '力量型狂热技能', '力量型狂熱技能', '파워 피버 스킬',
 'When attacking, high chance to trigger a Spike. Increases POW by 40%.',
 'アタック時、高確率でスパイクを発動。POWが40%アップ。',
 'When attacking, high chance to trigger a Spike. Increases POW by 40%.',
 '攻击时，高概率触发杀球。力量提升40%。',
 '攻擊時，高機率觸發殺球。力量提升40%。',
 '공격 시, 높은 확률로 스파이크 발동. 파워 40% 상승.',
 13, 'pow-boost-xl', 'パワーアップXL', 'Power Boost (XL)', '力量提升(特大)', '力量提升(特大)', '파워 업(XL)',
 'Increases POW by 20%.',
 'POWが20%アップ。',
 'Increases POW by 20%.',
 '力量提升20%。',
 '力量提升20%。',
 '파워 20% 상승.',
 24, 'victory-rush', 'ビクトリーラッシュ', 'Victory Rush', '胜利冲刺', '勝利衝刺', '빅토리 러시',
 'Each point won increases all stats by 5% (max 50%).',
 'ポイント獲得毎に全ステータスが5%アップ（最大50%）。',
 'Each point won increases all stats by 5% (max 50%).',
 '每赢一分全属性提升5%（最高50%）。',
 '每贏一分全屬性提升5%（最高50%）。',
 '포인트 획득마다 모든 스탯 5% 상승 (최대 50%).',
 'solar-flare-bromide', 'solar-flare-malfunction-bromide'),

-- Ayane - Midnight Shadow (SSR TEC)
(6, 'ayane', 'ssr-ayane-midnight-shadow',
 'ミッドナイトシャドウ', 'Midnight Shadow', '午夜阴影', '午夜陰影', '미드나이트 섀도우',
 'SSR', 'TEC',
 1300, 2000, 13,
 2100, 3300, 21,
 1400, 2100, 14,
 1200, 1900, 12,
 2, 'fever-skill-tec-1', 'TECフィーバースキル', 'TEC Fever Skill', '技巧型狂热技能', '技巧型狂熱技能', '테크닉 피버 스킬',
 'When attacking, high chance to trigger a Feint. Increases TEC by 40%.',
 'アタック時、高確率でフェイントを発動。TECが40%アップ。',
 'When attacking, high chance to trigger a Feint. Increases TEC by 40%.',
 '攻击时，高概率触发佯攻。技巧提升40%。',
 '攻擊時，高機率觸發佯攻。技巧提升40%。',
 '공격 시, 높은 확률로 페인트 발동. 테크닉 40% 상승.',
 8, 'critical-hit', 'クリティカルヒット', 'Critical Hit', '致命一击', '致命一擊', '크리티컬 히트',
 'High chance to deal critical damage when attacking.',
 'アタック時、高確率でクリティカルダメージを与える。',
 'High chance to deal critical damage when attacking.',
 '攻击时高概率造成暴击伤害。',
 '攻擊時高機率造成暴擊傷害。',
 '공격 시 높은 확률로 크리티컬 데미지.',
 20, 'concentration-master', '集中力マスター', 'Concentration Master', '专注大师', '專注大師', '집중력 마스터',
 'Immune to opponent''s debuff effects for first 5 attacks.',
 '最初の5回のアタックまで相手のデバフ効果を無効化。',
 'Immune to opponent''s debuff effects for first 5 attacks.',
 '前5次攻击免疫对手的减益效果。',
 '前5次攻擊免疫對手的減益效果。',
 '처음 5회 공격까지 상대 디버프 효과 무효.',
 'midnight-shadow-bromide', 'midnight-shadow-malfunction-bromide');

-- ============================================================================
-- 4. EPISODES (With Renamed Fields)
-- ============================================================================

INSERT INTO `episodes` (
  `id`, `unique_key`,
  `name_jp`, `name_en`, `name_cn`, `name_tw`, `name_kr`,
  `type`, `release_data`, `release_version`
) VALUES
(1, 'main-story-chapter-1',
 '第1章：ヴィーナス諸島へようこそ', 'Chapter 1: Welcome to Venus Islands', '第1章：欢迎来到维纳斯群岛', '第1章：歡迎來到維納斯群島', '제1장: 비너스 제도에 오신 것을 환영합니다',
 'MAIN', '2020-04-01', '1.0.0'),

(2, 'main-story-chapter-2',
 '第2章：ビーチバレーの始まり', 'Chapter 2: The Beginning of Beach Volleyball', '第2章：沙滩排球的开始', '第2章：沙灘排球的開始', '제2장: 비치발리볼의 시작',
 'MAIN', '2020-04-01', '1.0.0'),

(3, 'main-story-chapter-3',
 '第3章：新しい仲間たち', 'Chapter 3: New Companions', '第3章：新伙伴们', '第3章：新夥伴們', '제3장: 새로운 동료들',
 'MAIN', '2020-05-15', '1.1.0'),

(4, 'character-marie-episode-1',
 'マリー・ローズ：お菓子の時間', 'Marie Rose: Sweets Time', '玛莉萝丝：甜点时间', '瑪莉蘿絲：甜點時間', '마리 로즈: 과자 시간',
 'CHARACTER', '2020-04-01', '1.0.0'),

(5, 'character-honoka-episode-1',
 'ほのか：ビーチバレーの練習', 'Honoka: Beach Volleyball Practice', '穗香：沙滩排球练习', '穗香：沙灘排球練習', '호노카: 비치발리볼 연습',
 'CHARACTER', '2020-04-01', '1.0.0'),

(6, 'character-kasumi-episode-1',
 'かすみ：忍者の修行', 'Kasumi: Ninja Training', '霞：忍者修行', '霞：忍者修行', '카스미: 닌자 수행',
 'CHARACTER', '2021-08-01', '1.8.0'),

(7, 'event-summer-festival-2023',
 '夏祭り2023：花火大会', 'Summer Festival 2023: Fireworks Display', '夏日祭典2023：烟花大会', '夏日祭典2023：煙火大會', '여름 축제 2023: 불꽃놀이',
 'EVENT', '2023-07-15', '4.10.0'),

(8, 'swimsuit-stellar-aquarius-story',
 'ステラ・アクエリアス：星降る夜', 'Stellar Aquarius: Starry Night', '星光水瓶：星降之夜', '星光水瓶：星降之夜', '스텔라 아쿠아리우스: 별이 내리는 밤',
 'SWIMSUIT', '2023-01-15', '4.5.0'),

(9, 'item-birthday-cake-story',
 'バースデーケーキ：特別な日', 'Birthday Cake: Special Day', '生日蛋糕：特别的日子', '生日蛋糕：特別的日子', '생일 케이크: 특별한 날',
 'ITEM', '2022-06-06', '4.1.0'),

(10, 'main-story-chapter-4',
 '第4章：トーナメント開幕', 'Chapter 4: Tournament Begins', '第4章：锦标赛开幕', '第4章：錦標賽開幕', '제4장: 토너먼트 개막',
 'MAIN', '2020-06-20', '1.2.0');

